# Generated by Django 6.1.1 on 2026-09-21 15:12

import analytics_api.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('id', models.CharField(default=analytics_api.models.generate_custom_id, max_length=64, primary_key=True, serialize=False)),
                ('fund_code', models.CharField(max_length=64, unique=True)),
                ('fund_name', models.CharField(max_length=255)),
                ('fund_house', models.CharField(max_length=255)),
                ('fund_manager_id', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('EQUITY', 'Equity'), ('DEBT', 'Debt'), ('HYBRID', 'Hybrid'), ('ELSS', 'ELSS'), ('INDEX', 'Index'), ('LIQUID', 'Liquid'), ('SECTORAL', 'Sectoral')], max_length=64)),
                ('risk_level', models.CharField(choices=[('LOW', 'Low'), ('MODERATE', 'Moderate'), ('HIGH', 'High'), ('VERY_HIGH', 'Very High')], max_length=64)),
                ('current_nav', models.FloatField()),
                ('nav_updated_at', models.CharField(max_length=64)),
                ('min_investment', models.FloatField()),
                ('min_sip_amount', models.FloatField()),
                ('expense_ratio', models.FloatField()),
                ('exit_load_percent', models.FloatField(default=0.0)),
                ('exit_load_period_days', models.IntegerField(default=0)),
                ('inception_date', models.CharField(max_length=64)),
                ('aum_crores', models.FloatField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'funds',
            },
        ),
        migrations.CreateModel(
            name='SIPSchedule',
            fields=[
                ('id', models.CharField(default=analytics_api.models.generate_custom_id, max_length=64, primary_key=True, serialize=False)),
                ('investor_name', models.CharField(max_length=255)),
                ('fund_name', models.CharField(max_length=255)),
                ('amount', models.FloatField()),
                ('date', models.IntegerField()),
                ('status', models.CharField(default='ACTIVE', max_length=64)),
                ('next_debit', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'sip_schedules',
            },
        ),
        migrations.CreateModel(
            name='SystemUser',
            fields=[
                ('id', models.CharField(default=analytics_api.models.generate_custom_id, max_length=64, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('role', models.CharField(max_length=64)),
                ('status', models.CharField(default='ACTIVE', max_length=64)),
            ],
            options={
                'db_table': 'system_users',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(default=analytics_api.models.generate_custom_id, max_length=64, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('phone', models.CharField(max_length=64, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('full_name', models.CharField(max_length=255)),
                ('date_of_birth', models.CharField(max_length=64)),
                ('role', models.CharField(choices=[('INVESTOR', 'Investor'), ('COMPLIANCE_OFFICER', 'Compliance Officer'), ('ANALYST', 'Analyst'), ('FUND_MANAGER', 'Fund Manager')], default='INVESTOR', max_length=64)),
                ('status', models.CharField(choices=[('PENDING_VERIFICATION', 'Pending Verification'), ('VERIFIED', 'Verified'), ('KYC_SUBMITTED', 'KYC Submitted'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('DEACTIVATED', 'Deactivated')], default='PENDING_VERIFICATION', max_length=64)),
                ('mfa_enabled', models.BooleanField(default=False)),
                ('mfa_secret', models.CharField(blank=True, max_length=255, null=True)),
                ('device_fingerprint', models.CharField(blank=True, max_length=255, null=True)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.CharField(default=analytics_api.models.generate_custom_id, max_length=64, primary_key=True, serialize=False)),
                ('actor_id', models.CharField(blank=True, max_length=64, null=True)),
                ('actor_type', models.CharField(choices=[('USER', 'User'), ('SYSTEM', 'System'), ('AI_ENGINE', 'AI Engine'), ('CRON_JOB', 'Cron Job')], max_length=64)),
                ('actor_name', models.CharField(max_length=255)),
                ('entity_type', models.CharField(max_length=255)),
                ('entity_id', models.CharField(max_length=64)),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('READ', 'Read'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('VERIFY', 'Verify'), ('APPROVE', 'Approve'), ('REJECT', 'Reject')], max_length=64)),
                ('changes', models.TextField(blank=True, null=True)),
                ('ip_address', models.CharField(default='127.0.0.1', max_length=64)),
                ('user_agent', models.CharField(blank=True, max_length=512, null=True)),
                ('session_id', models.CharField(blank=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'audit_logs',
                'indexes': [models.Index(fields=['actor_id'], name='idx_audit_logs_actor')],
            },
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.CharField(default=analytics_api.models.generate_custom_id, max_length=64, primary_key=True, serialize=False)),
                ('fund_name', models.CharField(max_length=255)),
                ('investment_type', models.CharField(choices=[('LUMPSUM', 'Lumpsum'), ('SIP', 'SIP'), ('STP', 'STP'), ('SWP', 'SWP')], max_length=64)),
                ('amount', models.FloatField()),
                ('frequency', models.CharField(blank=True, max_length=64, null=True)),
                ('sip_date', models.IntegerField(blank=True, null=True)),
                ('mandate_status', models.CharField(blank=True, max_length=64, null=True)),
                ('start_date', models.CharField(max_length=64)),
                ('end_date', models.CharField(blank=True, max_length=64, null=True)),
                ('total_units', models.FloatField(default=0.0)),
                ('current_value', models.FloatField(default=0.0)),
                ('status', models.CharField(default='ACTIVE', max_length=64)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='investments', to='analytics_api.fund')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='investments', to='analytics_api.user')),
            ],
            options={
                'db_table': 'investments',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.CharField(default=analytics_api.models.generate_custom_id, max_length=64, primary_key=True, serialize=False)),
                ('fund_name', models.CharField(max_length=255)),
                ('transaction_type', models.CharField(max_length=64)),
                ('amount', models.FloatField()),
                ('nav_applied', models.FloatField(blank=True, null=True)),
                ('units', models.FloatField(blank=True, null=True)),
                ('stamp_duty', models.FloatField(default=0.0)),
                ('exit_load', models.FloatField(default=0.0)),
                ('status', models.CharField(default='INITIATED', max_length=64)),
                ('payment_ref', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_mode', models.CharField(blank=True, max_length=255, null=True)),
                ('settlement_date', models.CharField(blank=True, max_length=64, null=True)),
                ('folio_number', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('fund', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='transactions', to='analytics_api.fund')),
                ('investment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='transactions', to='analytics_api.investment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='transactions', to='analytics_api.user')),
            ],
            options={
                'db_table': 'transactions',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.CharField(default=analytics_api.models.generate_custom_id, max_length=64, primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('EMAIL', 'Email'), ('SMS', 'SMS'), ('PUSH', 'Push'), ('IN_APP', 'In-App')], max_length=64)),
                ('type', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='analytics_api.user')),
            ],
            options={
                'db_table': 'notifications',
            },
        ),
        migrations.CreateModel(
            name='KYCRecord',
            fields=[
                ('id', models.CharField(default=analytics_api.models.generate_custom_id, max_length=64, primary_key=True, serialize=False)),
                ('pan_number', models.CharField(max_length=255)),
                ('aadhaar_number', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('AI_PROCESSING', 'AI Processing'), ('AUTO_APPROVED', 'Auto Approved'), ('ESCALATED', 'Escalated'), ('COMPLIANCE_APPROVED', 'Compliance Approved'), ('REJECTED', 'Rejected')], default='SUBMITTED', max_length=64)),
                ('ai_confidence_score', models.FloatField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('verified_by', models.CharField(blank=True, max_length=64, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('attempt_number', models.IntegerField(default=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='kyc_records', to='analytics_api.user')),
            ],
            options={
                'db_table': 'kyc_records',
            },
        ),
        migrations.CreateModel(
            name='ComplianceCheck',
            fields=[
                ('id', models.CharField(default=analytics_api.models.generate_custom_id, max_length=64, primary_key=True, serialize=False)),
                ('check_type', models.CharField(max_length=255)),
                ('risk_score', models.FloatField()),
                ('result', models.CharField(choices=[('CLEAR', 'Clear'), ('SUSPICIOUS', 'Suspicious'), ('BLOCKED', 'Blocked')], max_length=64)),
                ('details', models.TextField()),
                ('checked_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='compliance_checks', to='analytics_api.transaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='compliance_checks', to='analytics_api.user')),
            ],
            options={
                'db_table': 'compliance_checks',
            },
        ),
        migrations.CreateModel(
            name='ComplianceAlert',
            fields=[
                ('id', models.CharField(default=analytics_api.models.generate_custom_id, max_length=64, primary_key=True, serialize=False)),
                ('alert_type', models.CharField(max_length=255)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], max_length=64)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('UNDER_REVIEW', 'Under Review'), ('RESOLVED', 'Resolved'), ('STR_FILED', 'STR Filed'), ('DISMISSED', 'Dismissed')], default='OPEN', max_length=64)),
                ('assigned_to', models.CharField(blank=True, max_length=64, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('compliance_check', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='alerts', to='analytics_api.compliancecheck')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='compliance_alerts', to='analytics_api.user')),
            ],
            options={
                'db_table': 'compliance_alerts',
            },
        ),
        migrations.CreateModel(
            name='CFAApproval',
            fields=[
                ('id', models.CharField(default=analytics_api.models.generate_custom_id, max_length=64, primary_key=True, serialize=False)),
                ('cfa_approval_code', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired')], default='PENDING', max_length=64)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('kyc_record', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='cfa_approvals', to='analytics_api.kycrecord')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='cfa_approvals', to='analytics_api.user')),
            ],
            options={
                'db_table': 'cfa_approvals',
            },
        ),
        migrations.CreateModel(
            name='KYCDocument',
            fields=[
                ('id', models.CharField(default=analytics_api.models.generate_custom_id, max_length=64, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('PAN', 'PAN Card'), ('AADHAAR', 'Aadhaar Card'), ('ADDRESS_PROOF', 'Address Proof'), ('PHOTOGRAPH', 'Photograph'), ('BANK_STATEMENT', 'Bank Statement')], max_length=64)),
                ('file_path', models.CharField(max_length=512)),
                ('file_hash', models.CharField(max_length=255)),
                ('file_size_bytes', models.IntegerField()),
                ('mime_type', models.CharField(max_length=64)),
                ('ocr_extracted_data', models.TextField(blank=True, null=True)),
                ('ai_authenticity_score', models.FloatField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('kyc_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='analytics_api.kycrecord')),
            ],
            options={
                'db_table': 'kyc_documents',
                'indexes': [models.Index(fields=['kyc_record'], name='idx_kyc_docs_record_id')],
            },
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user'], name='idx_transactions_user_id'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['investment'], name='idx_transactions_inv_id'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user'], name='idx_notifications_user'),
        ),
        migrations.AddIndex(
            model_name='kycrecord',
            index=models.Index(fields=['user'], name='idx_kyc_records_user_id'),
        ),
        migrations.AddIndex(
            model_name='investment',
            index=models.Index(fields=['user'], name='idx_investments_user_id'),
        ),
        migrations.AddIndex(
            model_name='investment',
            index=models.Index(fields=['fund'], name='idx_investments_fund_id'),
        ),
        migrations.AddIndex(
            model_name='compliancecheck',
            index=models.Index(fields=['transaction'], name='idx_comp_checks_txn'),
        ),
        migrations.AddIndex(
            model_name='compliancealert',
            index=models.Index(fields=['user'], name='idx_comp_alerts_user'),
        ),
    ]
